In [ ]:
#1
listaname=[]
listaage=[]
name=str(input("Ingrese el nombre: "))
age=int(input("Ingrese la edad: "))
listaname.append(name)
listaage.append(age)
decision=str(input("¿Desea añadir mas datos?: "))
while decision=="si" or decision=="Si" or decision=="sí" or decision=="Sí":
  name=str(input("Ingrese el nombre: "))
  age=int(input("Ingrese la edad: "))
  listaname.append(name)
  listaage.append(age)
  decision=str(input("¿Desea añadir mas datos?: "))
print("//////////////////")
for x,y in zip(listaname,listaage):
  print(x,y)

In [ ]:
#1.2
import matplotlib.pyplot as plt
import numpy as np
coo=np.arange(len(listaage))
anc=0.30
fig, ax=plt.subplots()
#ax.bar(Coordenadas,Altura,Ancho)
ax.bar(coo,listaage,anc)
ax.set_title("Grafico de barras")
ax.set_ylabel("Edad")
ax.set_xlabel("Nombre")
ax.set_xticks(coo)
ax.set_xticklabels(listaname)
for i,j in zip(coo,listaage):
  ax.annotate(j, xy=(i-0.05,j+0.2))

In [ ]:
#1.3
import matplotlib.pyplot as plt
import numpy as np
coo=np.arange(len(listaage))
fig, ax=plt.subplots()
#plt.plot(valorx,valory)
plt.plot(listaname,listaage)
ax.set_xlabel("Nombre")
ax.set_ylabel("Edad")
ax.set_title("Grafico de lineas")
for i,j in zip(coo,listaage):
  ax.annotate(j, xy=(i-0.05,j+0.2))

In [ ]:
#1.4
import matplotlib.pyplot as plt
import numpy as np
gf, ax=plt.subplots()
#plt.scatter(valorx,valory)
plt.scatter(listaname,listaage)
ax.set_title("Grafico de puntos")
ax.set_ylabel("Edad")
ax.set_xlabel("Nombre")
for i,j in zip(coo,listaage):
  ax.annotate(j, xy=(i-0.1,j+0.05))

In [ ]:
#2
listax=[]
listay=[]
a=-100
b=100
c=-100
while c>=a and c<=b:
  d=c**3
  listax.append(c)
  listay.append(d)
  c=c+1
for x,y in zip(listax,listay):
  print(x,y)

In [ ]:
#2.2
import matplotlib.pyplot as plt
import numpy as np
coor=np.arange(len(listay))
an=0.35
gf, ax=plt.subplots(figsize=(50,30))
ax.bar(coor,listay,an)
ax.set_xticks(coor)
ax.set_xticklabels(listax)
ax.set_title("Grafico de barras")
ax.set_xlabel("X")
ax.set_ylabel("X**3")

In [ ]:
#2.3
import matplotlib.pyplot as plt
gf, ax=plt.subplots()
plt.plot(listax,listay)
ax.set_title("Grafico de lineas")
ax.set_xlabel("X")
ax.set_ylabel("X**3")

In [ ]:
#2.4
import matplotlib.pyplot as plt
gf, ax=plt.subplots(figsize=(20,10))
plt.scatter(listax,listay)
ax.set_title("Grafico de puntos")
ax.set_xlabel("X")
ax.set_ylabel("X**3")

In [ ]:
#3
import matplotlib.pyplot as plt
import numpy as np
from random import randint
listaA=[]
listaB=[]
a=1
b=20
c=1
while c>=a and c<=b:
  d=randint(1,6)
  listaA.append(c)
  listaB.append(d)
  c=c+1
for x,y in zip(listaA,listaB):
  print(x,y)

In [ ]:
#3.2
import matplotlib.pyplot as plt
import numpy as np
anch=0.35
coord=np.arange(len(listaB))
gf, ax=plt.subplots()
ax.bar(coord,listaB,anch)
ax.set_xticks(coord)
ax.set_xticklabels(listaA)
ax.set_title("Grafico de barras")
ax.set_xlabel("X")
ax.set_ylabel("Y")

In [ ]:
#3.3
import numpy as np
listaC=listaA+listaB
listaC=np.array(listaC)
print("La media es: ",np.mean(listaC))
print("La mediana es: ",np.median(listaC))
print("La desviación estandar en Y es de: ",np.std(listaB))

In [ ]:
#4 

mat=[[6261,	7221,	5709,	4486,	1647,	5989,	2850],
[205,	7173,	6517,	5993,	604,	870,	1904],
[6801,	5094,	7133,	4439,	1902,	2198,	2362],
[4314,	3046,	1593,	1242,	5101,	9754,	846],
[9262,	9015,	3361,	8915,	9209,	8396,	8823],
[6165,	1014,	4380,	5556,	814,	6389,	5989],
[9277,	9332,	2928,	3573,	5167,	6451,	108],
[4593,	2368,	916,	7995,	6224,	5137,	9192],
[1764,	2904,	6232,	1130,	261,	2051,	2417],
[1021,	5397,	4138,	2718,	6273,	7871,	6382],
[1988,	3178,	7420,	2767,	8390,	7708,	2469],
[6044,	8315,	1848,	5761,	3492,	7600,	9150]]
import pandas as pd
pdf=pd.DataFrame(mat)
pdf.describe()

In [ ]:
#4.2
i=2
Mach3=[fila[i]for fila in mat]
mes=["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"]
import matplotlib.pyplot as plt
import numpy as np
ancho=0.35
coorde=np.arange(len(Mach3))
gf, ax=plt.subplots(figsize=(20,12))
ax.bar(coorde,Mach3,ancho)
ax.set_title("Maquina 3")
ax.set_xlabel("Mes")
ax.set_ylabel("#U.Producidas")
ax.set_xticks(coorde)
ax.set_xticklabels(mes)
for i,j in zip(coorde,Mach3):
  ax.annotate(j, xy=(i-0.15,j))

In [1]:
#5
import numpy as np
n=int(input("Ingrese el valor de n: "))
Matriz=np.random.randint(10,99,size=(n,n))
print(Matriz)

Ingrese el valor de n: 3
[[71 30 21]
 [89 97 94]
 [11 58 15]]


In [ ]:
#5.2
mp=[]
ms=[]
import matplotlib.pyplot as plt
import numpy as np
for i in range(n):
  #Primer valor renglón. Segundo valor columna.
  mp.append(Matriz[i][i])
  ms.append(Matriz[i][n-i-1])
print("Diagonal principal: ",mp)
print("Diagonal secundaria: ",ms)
gf, ax=plt.subplots()
plt.scatter(mp,ms)
ax.set_xticks(mp)
ax.set_title("Elementos de las diagonales")
ax.set_xlabel("Diagonal principal")
ax.set_ylabel("Diagonal secundaria")

In [ ]:
#5.3
import pandas as pd
pdf=pd.DataFrame(Matriz)
pdf.describe()